"""Content Desk — Planner sheet sync.

Fetches the "Planable CSV Output" tab of the reference Google Sheet and
writes ../app/planner-data.js (window.PLANNER_ROWS). The planner screen
mirrors that tab: videos on the left, pictures on the right.

The sheet is link-viewable, so this is a plain unauthenticated CSV
download — no Drive token needed.

Tab columns (Planable CSV Output):
  A title  B text  C video date  D posted-flag  E (unused)  F (blank)
  G description  H quote  I picture date  J attachment
"""
import csv
import io
import json
import os
import urllib.request
from datetime import datetime

# Google exports date cells in the sheet's display format — normalise them
# all to ISO so the planner and dashboard can compare/sort them.
_DATE_FORMATS = [
    ("%Y %b %d, %I:%M %p", True),
    ("%Y %B %d, %I:%M %p", True),
    ("%Y-%m-%d %H:%M:%S", True),
    ("%m/%d/%Y %H:%M:%S", True),
    ("%m/%d/%Y %I:%M:%S %p", True),
    ("%Y %b %d", False),
    ("%m/%d/%Y", False),
    ("%Y-%m-%d", False),
]


def normalize_date(s):
    s = (s or "").strip()
    if not s:
        return ""
    for fmt, has_time in _DATE_FORMATS:
        try:
            dt = datetime.strptime(s, fmt)
            return dt.strftime("%Y-%m-%d %H:%M:%S" if has_time else "%Y-%m-%d")
        except ValueError:
            continue
    return s

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.join(HERE, "..", "app", "planner-data.js")

SHEET_ID = "1Mv6aP79QkgYa0hX82RCrfL71xAtKS4iOHt8p1ThGQ8Y"
GID = "1086017697"  # "Planable CSV Output" tab
CSV_URL = (f"https://docs.google.com/spreadsheets/d/{SHEET_ID}"
           f"/export?format=csv&gid={GID}")


def fetch_csv():
    req = urllib.request.Request(CSV_URL, headers={"User-Agent": "ContentDesk"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        final = resp.geturl()
        if "accounts.google.com" in final or "ServiceLogin" in final:
            raise RuntimeError(
                "Sheet is not link-viewable. In the sheet: Share -> General "
                "access -> 'Anyone with the link' -> Viewer.")
        return resp.read().decode("utf-8", errors="replace")


def clean(v):
    return (v or "").strip()


def main():
    text = fetch_csv()
    reader = list(csv.reader(io.StringIO(text)))
    rows = []
    n = 0
    # Row 1 = header, row 2 = blank spacer; data starts at row 3.
    for idx, raw in enumerate(reader[2:], start=3):
        cell = lambda c: clean(raw[c]) if c < len(raw) else ""
        title, text_, vdate = cell(0), cell(1), normalize_date(cell(2))
        flag = cell(3)
        desc, quote = cell(6), cell(7)
        pdate, attach = normalize_date(cell(8)), cell(9)

        has_video = bool(title)
        has_picture = bool(desc or quote or attach)
        if not (has_video or has_picture):
            continue
        n += 1

        flag_low = flag.lower()
        posted = flag_low in ("1", "1.0", "true", "yes")

        rows.append({
            "n": n,
            "sheetRow": idx,
            "video": {"title": title, "text": text_, "dateTime": vdate}
            if has_video else None,
            "picture": {"description": desc, "quote": quote,
                        "dateTime": pdate, "attachment": attach}
            if has_picture else None,
            "posted": posted,
            "postedRaw": flag,
        })

    banner = ("// AUTO-GENERATED by drive-sync/sheet-sync.py — do not edit by hand.\n"
              "// Mirror of the 'Planable CSV Output' tab of the reference sheet.\n")
    body = "window.PLANNER_ROWS = " + json.dumps(rows, indent=1) + ";\n"
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(banner + body)

    videos = sum(1 for r in rows if r["video"])
    pics = sum(1 for r in rows if r["picture"])
    posted = sum(1 for r in rows if r["posted"])
    print(f"Planner rows : {len(rows)}")
    print(f"  videos     : {videos}")
    print(f"  pictures   : {pics}")
    print(f"  posted (D=1): {posted}")
    print(f"Wrote {os.path.relpath(OUT_PATH, HERE)}")


if __name__ == "__main__":
    main()
