"""Content Desk — Google Drive asset sync.

Self-contained. Reads credentials.json / token.json from THIS folder only,
never from Footage Brain. Walks the client content folder and writes
../app/drive-assets.js, which Content Desk loads as window.DRIVE_ASSETS.

Scope is metadata.readonly — names and file metadata only, no downloads.
"""
import json
import os
import socket
import time

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

socket.setdefaulttimeout(120)

HERE = os.path.dirname(os.path.abspath(__file__))
SCOPES = ["https://www.googleapis.com/auth/drive.metadata.readonly"]
FOLDER_MIME = "application/vnd.google-apps.folder"

# Client content assets folder (Content Desk's own — not Footage Brain footage).
ROOT_FOLDER_ID = "1viPWTb6peGAQQTnDlbFg-MsJPJB7lZ_d"

OUT_PATH = os.path.join(HERE, "..", "app", "drive-assets.js")

VIDEO_EXTS = {".mp4", ".mov", ".mxf", ".avi", ".mkv", ".mpg", ".mpeg",
              ".mts", ".m2ts", ".wmv", ".webm", ".insv", ".m4v", ".3gp"}
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".heic", ".heif", ".webp",
              ".gif", ".tiff", ".bmp"}


def get_service():
    creds = None
    token_path = os.path.join(HERE, "token.json")
    if os.path.exists(token_path):
        creds = Credentials.from_authorized_user_file(token_path, SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                os.path.join(HERE, "credentials.json"), SCOPES)
            creds = flow.run_local_server(port=0)
        with open(token_path, "w") as f:
            f.write(creds.to_json())
    return build("drive", "v3", credentials=creds)


def list_children(service, folder_id):
    items, page_token = [], None
    while True:
        for attempt in range(6):
            try:
                resp = service.files().list(
                    q=f"'{folder_id}' in parents and trashed=false",
                    pageSize=1000,
                    pageToken=page_token,
                    includeItemsFromAllDrives=True,
                    supportsAllDrives=True,
                    fields=("nextPageToken, files(id,name,mimeType,size,"
                            "createdTime,modifiedTime,webViewLink)"),
                ).execute(num_retries=3)
                break
            except (TimeoutError, socket.timeout, ConnectionError, OSError) as e:
                wait = 2 ** attempt
                print(f"  transient error ({e}); retry {attempt + 1}/6 in {wait}s")
                time.sleep(wait)
        else:
            raise RuntimeError(f"failed to list folder {folder_id}")
        items.extend(resp.get("files", []))
        page_token = resp.get("nextPageToken")
        if not page_token:
            break
    return items


def classify(name, mime):
    ext = os.path.splitext(name)[1].lower()
    if mime.startswith("video/") or ext in VIDEO_EXTS:
        return "video"
    if mime.startswith("image/") or ext in IMAGE_EXTS:
        return "image"
    return None


assets = []
folders_seen = 0


def walk(service, folder_id, path):
    global folders_seen
    for item in list_children(service, folder_id):
        name = item.get("name", "")
        if item.get("mimeType") == FOLDER_MIME:
            folders_seen += 1
            walk(service, item["id"], path + [name])
            continue
        kind = classify(name, item.get("mimeType", ""))
        if not kind:
            continue
        assets.append({
            "driveId": item.get("id"),
            "filename": name,
            "type": kind,
            "driveFolder": "/".join(path) if path else "",
            "sizeBytes": int(item["size"]) if item.get("size") else None,
            "createdTime": item.get("createdTime"),
            "modifiedTime": item.get("modifiedTime"),
            "webViewLink": item.get("webViewLink"),
        })


def main():
    service = get_service()
    print(f"Scanning Drive folder {ROOT_FOLDER_ID} ...")
    walk(service, ROOT_FOLDER_ID, [])
    assets.sort(key=lambda a: (a["driveFolder"], a["filename"].lower()))

    banner = ("// AUTO-GENERATED by drive-sync/sync.py — do not edit by hand.\n"
              "// Real Google Drive asset metadata (names only, read-only scope).\n")
    body = "window.DRIVE_ASSETS = " + json.dumps(assets, indent=2) + ";\n"
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(banner + body)

    videos = sum(1 for a in assets if a["type"] == "video")
    images = sum(1 for a in assets if a["type"] == "image")
    print(f"\nFolders walked : {folders_seen}")
    print(f"Assets found   : {len(assets)}  ({videos} video, {images} image)")
    folder_set = sorted({a["driveFolder"] for a in assets})
    print(f"Subfolders with assets ({len(folder_set)}):")
    for fp in folder_set:
        n = sum(1 for a in assets if a["driveFolder"] == fp)
        print(f"  [{n:3}]  {fp or '(root)'}")
    print(f"\nWrote {os.path.relpath(OUT_PATH, HERE)}")


if __name__ == "__main__":
    main()
